/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Program to test current driver implementation to handle GPIO. Will work on port D to test LEDs.
int main(void)
{
	GPIO_Handle_t pD12, pD13, pD14, pD15;

	pD12.pGPIOx = GPIOD;
	pD12.PinConfig.PinNumber = GPIO_PIN_12;
	pD12.PinConfig.PinMode = GPIO_MODER_OUT;
	pD12.PinConfig.PinSpeed = GPIO_SPEEDR_LOW;
	pD12.PinConfig.PinPuPdControl = GPIO_PUPDR_NONE; //Internal pin is push-pull no need for pull-up/down resistors.
	pD12.PinConfig.PinOPType = GPIO_OTYPER_PP;

	pD13.pGPIOx = GPIOD;
	pD13.PinConfig.PinNumber = GPIO_PIN_13;
	pD13.PinConfig.PinMode = GPIO_MODER_OUT;
	pD13.PinConfig.PinSpeed = GPIO_SPEEDR_LOW;
	pD13.PinConfig.PinPuPdControl = GPIO_PUPDR_NONE; //Internal pin is push-pull no need for pull-up/down resistors.
	pD13.PinConfig.PinOPType = GPIO_OTYPER_PP;


	pD14.pGPIOx = GPIOD;
	pD14.PinConfig.PinNumber = GPIO_PIN_14;
	pD14.PinConfig.PinMode = GPIO_MODER_OUT;
	pD14.PinConfig.PinSpeed = GPIO_SPEEDR_LOW;
	pD14.PinConfig.PinPuPdControl = GPIO_PUPDR_NONE; //Internal pin is push-pull no need for pull-up/down resistors.
	pD14.PinConfig.PinOPType = GPIO_OTYPER_PP;

	pD15.pGPIOx = GPIOD;
	pD15.PinConfig.PinNumber = GPIO_PIN_15;
	pD15.PinConfig.PinMode = GPIO_MODER_OUT;
	pD15.PinConfig.PinSpeed = GPIO_SPEEDR_LOW;
	pD15.PinConfig.PinPuPdControl = GPIO_PUPDR_NONE; //Internal pin is push-pull no need for pull-up/down resistors.
	pD15.PinConfig.PinOPType = GPIO_OTYPER_PP;

	GPIO_CLK(&pD12, ENABLE); // NOTE: Clock will be already active for whole port D, so pd13 can be used already.
	GPIO_Init(&pD12);
	GPIO_Init(&pD13);
	GPIO_Init(&pD14);
	GPIO_Init(&pD15);

	// Alternate LED3 and LED4 lights.
	while (1) {
		GPIO_TogglePin(&pD12);
		 for (volatile int i = 0; i < 1000000; i++);
		GPIO_TogglePin(&pD13);
		 for (volatile int i = 0; i < 1000000; i++);
		GPIO_TogglePin(&pD14);
		 for (volatile int i = 0; i < 1000000; i++);
        GPIO_TogglePin(&pD15);
	}
}
